import type { IgnoreRuleSet } from './types'

export default {
    binaryExtensions: [
        '.7z',
        '.avif',
        '.bin',
        '.bmp',
        '.bz2',
        '.cer',
        '.crt',
        '.db',
        '.db-shm',
        '.db-wal',
        '.der',
        '.doc',
        '.docx',
        '.dll',
        '.dylib',
        '.dsym',
        '.exe',
        '.flac',
        '.gif',
        '.gz',
        '.heic',
        '.heif',
        '.ico',
        '.jpeg',
        '.jpg',
        '.key',
        '.lib',
        '.m4a',
        '.mkv',
        '.mov',
        '.mp3',
        '.mp4',
        '.o',
        '.obj',
        '.otf',
        '.pdf',
        '.pem',
        '.pfx',
        '.png',
        '.ppt',
        '.pptx',
        '.rar',
        '.sqlite',
        '.sqlite3',
        '.so',
        '.tar',
        '.tgz',
        '.tif',
        '.tiff',
        '.ttf',
        '.wasm',
        '.wav',
        '.webp',
        '.woff',
        '.woff2',
        '.xls',
        '.xlsx',
        '.xz',
        '.zip',
        '.zst',
    ],
    directoryNames: [
        '.build',
        '.bundle',
        '.cache',
        '.git',
        '.hg',
        '.idea',
        '.konteks',
        '.svn',
        'build',
        'coverage',
        'dist',
        'out',
        'vendor',
    ],
    fileNames: ['.DS_Store', '.env', 'memory.sqlite'],
    generatedFileSuffixes: ['.map'],
    generatedPathFragments: [
        '/__generated__/',
        '/build/generated/',
        '/gen/',
        '/generated/',
    ],
    minifiedFileSuffixes: ['.min.js', '.min.css', '.min.mjs', '.min.cjs'],
    secretExtensions: ['.der', '.key', '.p12', '.pem', '.pfx'],
    secretFileNames: [
        '.envrc',
        '.netrc',
        '.npmrc',
        '.pypirc',
        '.sentryclirc',
        '.yarnrc',
        '.yarnrc.yml',
    ],
} satisfies IgnoreRuleSet
